import type { ActivityFeedItem } from "@/types/command-types";

const mk = (
  idx: number,
  source: ActivityFeedItem["source"],
  level: ActivityFeedItem["level"],
  title: string,
  message: string,
  regionId?: string,
  siteId?: string,
  buildingId?: string,
): ActivityFeedItem => ({
  id: `demo-${idx}`,
  timestamp: new Date(Date.now() + idx * 1000 * 18).toISOString(),
  source,
  level,
  title,
  message,
  regionId,
  siteId,
  buildingId,
});

export const DEMO_MODE_SCRIPT: ActivityFeedItem[] = [
  mk(
    1,
    "signal",
    "warning",
    "Conflict Cluster Detected",
    "Regional conflict pressure accelerated across Eastern Mediterranean and Persian Gulf corridors.",
    "east_med",
  ),
  mk(
    2,
    "risk",
    "warning",
    "Regional Risk Updated",
    "Eastern Mediterranean risk moved into elevated band due to conflict + infrastructure stress coupling.",
    "east_med",
  ),
  mk(
    3,
    "cascade",
    "critical",
    "Cascade Trigger",
    "Power-dispatch dependency stress propagated into medical and telecom nodes.",
    "east_med",
  ),
  mk(
    4,
    "system",
    "info",
    "Site Drill-down Ready",
    "Eastern Mediterranean operations cluster is now active for local simulation.",
    "east_med",
    "east_med-ops-cluster",
  ),
  mk(
    5,
    "simulation",
    "warning",
    "Local Fire Simulation",
    "Fire scenario generated for active building with constrained egress and rising smoke envelope.",
    "east_med",
    "east_med-ops-cluster",
    "east_med-building-1",
  ),
  mk(
    6,
    "signal",
    "warning",
    "Secondary Theater Escalation",
    "Persian Gulf corridor received correlated conflict and infrastructure disruption signals.",
    "persian_gulf",
  ),
  mk(
    7,
    "risk",
    "critical",
    "Risk Surge",
    "Persian Gulf risk crossed critical threshold as route pressure intensified.",
    "persian_gulf",
  ),
  mk(
    8,
    "system",
    "info",
    "Site Drill-down Ready",
    "Gulf Infrastructure Park prepared for flood stress simulation.",
    "persian_gulf",
    "gulf-infra-park",
  ),
  mk(
    9,
    "simulation",
    "warning",
    "Local Flood Simulation",
    "Flood scenario generated with rapid ingress and compromised low-level utility access.",
    "persian_gulf",
    "gulf-infra-park",
    "gulf-data-hub-7",
  ),
  mk(
    10,
    "signal",
    "warning",
    "Global Spread Watch",
    "Black Sea and adjacent corridors show emerging second-wave risk signatures.",
    "black_sea",
  ),
  mk(
    11,
    "cascade",
    "warning",
    "Predicted Cascade Expansion",
    "Transport and hospital dependencies show elevated next-wave failure probability.",
    "black_sea",
  ),
  mk(
    12,
    "simulation",
    "critical",
    "Demo Sequence Complete",
    "Multi-scale flow validated: Global -> Regional -> Site -> Building incident response.",
    "black_sea",
    "black_sea-ops-cluster",
    "black_sea-building-1",
  ),
];
